version: '3.4'

services:
  flowable-db:
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - data_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flowable
      - POSTGRES_USER=flowable
      - POSTGRES_PASSWORD=flowable

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.0
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - data_es:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - node.name=flowable-node
      - cluster.name=flowable-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  data_db:
  data_es:
